// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// sum_tau_DeepState_TestHarness_generation.cpp and sum_tau_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector sum_tau(double m, double theta, NumericVector phivar, NumericVector covariate, int K);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector m(1);
  m[0]  = RcppDeepState_double();
  qs::c_qsave(m,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/sum_tau/inputs/m.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "m values: "<< m << std::endl;
  NumericVector theta(1);
  theta[0]  = RcppDeepState_double();
  qs::c_qsave(theta,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/sum_tau/inputs/theta.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "theta values: "<< theta << std::endl;
  NumericVector phivar  = RcppDeepState_NumericVector();
  qs::c_qsave(phivar,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/sum_tau/inputs/phivar.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "phivar values: "<< phivar << std::endl;
  NumericVector covariate  = RcppDeepState_NumericVector();
  qs::c_qsave(covariate,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/sum_tau/inputs/covariate.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "covariate values: "<< covariate << std::endl;
  IntegerVector K(1);
  K[0]  = RcppDeepState_int();
  qs::c_qsave(K,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/sum_tau/inputs/K.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "K values: "<< K << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    sum_tau(m[0],theta[0],phivar,covariate,K[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
