// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// indexToGridCpp_DeepState_TestHarness_generation.cpp and indexToGridCpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix indexToGridCpp(IntegerVector idx, IntegerVector array_dim);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector idx  = RcppDeepState_IntegerVector();
  std::string idx_t = "/home/akhila/fuzzer_packages/fuzzedpackages/neuroim/inst/testfiles/indexToGridCpp/libFuzzer_indexToGridCpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_idx.qs";
  qs::c_qsave(idx,idx_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "idx values: "<< idx << std::endl;
  IntegerVector array_dim  = RcppDeepState_IntegerVector();
  std::string array_dim_t = "/home/akhila/fuzzer_packages/fuzzedpackages/neuroim/inst/testfiles/indexToGridCpp/libFuzzer_indexToGridCpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_array_dim.qs";
  qs::c_qsave(array_dim,array_dim_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "array_dim values: "<< array_dim << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    indexToGridCpp(idx,array_dim);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
