// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// getconfusion_DeepState_TestHarness_generation.cpp and getconfusion_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix getconfusion(NumericVector x, NumericVector y, NumericVector ux, NumericVector uy);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/mclustcomp/inst/testfiles/getconfusion/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector y  = RcppDeepState_NumericVector();
  qs::c_qsave(y,"/home/akhila/fuzzer_packages/fuzzedpackages/mclustcomp/inst/testfiles/getconfusion/inputs/y.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  NumericVector ux  = RcppDeepState_NumericVector();
  qs::c_qsave(ux,"/home/akhila/fuzzer_packages/fuzzedpackages/mclustcomp/inst/testfiles/getconfusion/inputs/ux.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ux values: "<< ux << std::endl;
  NumericVector uy  = RcppDeepState_NumericVector();
  qs::c_qsave(uy,"/home/akhila/fuzzer_packages/fuzzedpackages/mclustcomp/inst/testfiles/getconfusion/inputs/uy.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "uy values: "<< uy << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    getconfusion(x,y,ux,uy);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
