// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// fastlm_DeepState_TestHarness_generation.cpp and fastlm_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::colvec fastlm(NumericVector yr, NumericMatrix Xr);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector yr  = RcppDeepState_NumericVector();
  std::string yr_t = "/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/fastlm/AFL_fastlm/afl_inputs/" + std::to_string(t) + "_yr.qs";
  qs::c_qsave(yr,yr_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "yr values: "<< yr << std::endl;
  NumericMatrix Xr  = RcppDeepState_NumericMatrix();
  std::string Xr_t = "/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/fastlm/AFL_fastlm/afl_inputs/" + std::to_string(t) + "_Xr.qs";
  qs::c_qsave(Xr,Xr_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Xr values: "<< Xr << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    fastlm(yr,Xr);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
