// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// simulate_r_DeepState_TestHarness_generation.cpp and simulate_r_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List simulate_r(double n_days, double n_intraday, double alpha, double beta, double gamma, NumericVector Z, double h0);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector n_days(1);
  n_days[0]  = RcppDeepState_double();
  qs::c_qsave(n_days,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/simulate_r/inputs/n_days.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n_days values: "<< n_days << std::endl;
  NumericVector n_intraday(1);
  n_intraday[0]  = RcppDeepState_double();
  qs::c_qsave(n_intraday,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/simulate_r/inputs/n_intraday.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n_intraday values: "<< n_intraday << std::endl;
  NumericVector alpha(1);
  alpha[0]  = RcppDeepState_double();
  qs::c_qsave(alpha,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/simulate_r/inputs/alpha.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "alpha values: "<< alpha << std::endl;
  NumericVector beta(1);
  beta[0]  = RcppDeepState_double();
  qs::c_qsave(beta,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/simulate_r/inputs/beta.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "beta values: "<< beta << std::endl;
  NumericVector gamma(1);
  gamma[0]  = RcppDeepState_double();
  qs::c_qsave(gamma,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/simulate_r/inputs/gamma.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "gamma values: "<< gamma << std::endl;
  NumericVector Z  = RcppDeepState_NumericVector();
  qs::c_qsave(Z,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/simulate_r/inputs/Z.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Z values: "<< Z << std::endl;
  NumericVector h0(1);
  h0[0]  = RcppDeepState_double();
  qs::c_qsave(h0,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/simulate_r/inputs/h0.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "h0 values: "<< h0 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    simulate_r(n_days[0],n_intraday[0],alpha[0],beta[0],gamma[0],Z,h0[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
