// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ET0_ThornthwaiteWilmott_DeepState_TestHarness_generation.cpp and ET0_ThornthwaiteWilmott_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector ET0_ThornthwaiteWilmott(NumericVector temp, NumericVector doy, NumericVector latitude);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector temp  = RcppDeepState_NumericVector();
  qs::c_qsave(temp,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_ThornthwaiteWilmott/inputs/temp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "temp values: "<< temp << std::endl;
  NumericVector doy  = RcppDeepState_NumericVector();
  qs::c_qsave(doy,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_ThornthwaiteWilmott/inputs/doy.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "doy values: "<< doy << std::endl;
  NumericVector latitude  = RcppDeepState_NumericVector();
  qs::c_qsave(latitude,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_ThornthwaiteWilmott/inputs/latitude.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "latitude values: "<< latitude << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ET0_ThornthwaiteWilmott(temp,doy,latitude);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
