// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ricker_v_t_DeepState_TestHarness_generation.cpp and ricker_v_t_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double ricker_v_t(double spawners, double a, double b, double d, double v_t);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector spawners(1);
  spawners[0]  = RcppDeepState_double();
  std::string spawners_t = "/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/ricker_v_t/libFuzzer_ricker_v_t/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_spawners.qs";
  qs::c_qsave(spawners,spawners_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "spawners values: "<< spawners << std::endl;
  NumericVector a(1);
  a[0]  = RcppDeepState_double();
  std::string a_t = "/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/ricker_v_t/libFuzzer_ricker_v_t/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_a.qs";
  qs::c_qsave(a,a_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "a values: "<< a << std::endl;
  NumericVector b(1);
  b[0]  = RcppDeepState_double();
  std::string b_t = "/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/ricker_v_t/libFuzzer_ricker_v_t/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_b.qs";
  qs::c_qsave(b,b_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "b values: "<< b << std::endl;
  NumericVector d(1);
  d[0]  = RcppDeepState_double();
  std::string d_t = "/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/ricker_v_t/libFuzzer_ricker_v_t/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_d.qs";
  qs::c_qsave(d,d_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "d values: "<< d << std::endl;
  NumericVector v_t(1);
  v_t[0]  = RcppDeepState_double();
  std::string v_t_t = "/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/ricker_v_t/libFuzzer_ricker_v_t/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_v_t.qs";
  qs::c_qsave(v_t,v_t_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "v_t values: "<< v_t << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ricker_v_t(spawners[0],a[0],b[0],d[0],v_t[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
