// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ByteVectorToDoubles_DeepState_TestHarness_generation.cpp and ByteVectorToDoubles_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

DoubleVector ByteVectorToDoubles(IntegerVector b);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector b  = RcppDeepState_IntegerVector();
  qs::c_qsave(b,"/home/akhila/fuzzer_packages/fuzzedpackages/mcga/inst/testfiles/ByteVectorToDoubles/inputs/b.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "b values: "<< b << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ByteVectorToDoubles(b);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
