// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// VPD_DeepState_TestHarness_generation.cpp and VPD_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector VPD(NumericVector temp, NumericVector relh);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector temp  = RcppDeepState_NumericVector();
  qs::c_qsave(temp,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/VPD/inputs/temp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "temp values: "<< temp << std::endl;
  NumericVector relh  = RcppDeepState_NumericVector();
  qs::c_qsave(relh,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/VPD/inputs/relh.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "relh values: "<< relh << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    VPD(temp,relh);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
