// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// hourlyFromDailyTemp_DeepState_TestHarness_generation.cpp and hourlyFromDailyTemp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix hourlyFromDailyTemp(NumericVector tmin, NumericVector tmax, NumericVector doy, NumericVector latitude);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector tmin  = RcppDeepState_NumericVector();
  qs::c_qsave(tmin,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/hourlyFromDailyTemp/inputs/tmin.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tmin values: "<< tmin << std::endl;
  NumericVector tmax  = RcppDeepState_NumericVector();
  qs::c_qsave(tmax,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/hourlyFromDailyTemp/inputs/tmax.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tmax values: "<< tmax << std::endl;
  NumericVector doy  = RcppDeepState_NumericVector();
  qs::c_qsave(doy,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/hourlyFromDailyTemp/inputs/doy.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "doy values: "<< doy << std::endl;
  NumericVector latitude  = RcppDeepState_NumericVector();
  qs::c_qsave(latitude,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/hourlyFromDailyTemp/inputs/latitude.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "latitude values: "<< latitude << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    hourlyFromDailyTemp(tmin,tmax,doy,latitude);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
