// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// simulate_r_DeepState_TestHarness_generation.cpp and simulate_r_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List simulate_r(double n_days, double n_intraday, double alpha, double beta, double gamma, NumericVector Z, double h0);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector n_days(1);
  n_days[0]  = RcppDeepState_double();
  std::string n_days_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/simulate_r/libFuzzer_simulate_r/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_n_days.qs";
  qs::c_qsave(n_days,n_days_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n_days values: "<< n_days << std::endl;
  NumericVector n_intraday(1);
  n_intraday[0]  = RcppDeepState_double();
  std::string n_intraday_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/simulate_r/libFuzzer_simulate_r/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_n_intraday.qs";
  qs::c_qsave(n_intraday,n_intraday_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n_intraday values: "<< n_intraday << std::endl;
  NumericVector alpha(1);
  alpha[0]  = RcppDeepState_double();
  std::string alpha_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/simulate_r/libFuzzer_simulate_r/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_alpha.qs";
  qs::c_qsave(alpha,alpha_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "alpha values: "<< alpha << std::endl;
  NumericVector beta(1);
  beta[0]  = RcppDeepState_double();
  std::string beta_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/simulate_r/libFuzzer_simulate_r/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_beta.qs";
  qs::c_qsave(beta,beta_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "beta values: "<< beta << std::endl;
  NumericVector gamma(1);
  gamma[0]  = RcppDeepState_double();
  std::string gamma_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/simulate_r/libFuzzer_simulate_r/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_gamma.qs";
  qs::c_qsave(gamma,gamma_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "gamma values: "<< gamma << std::endl;
  NumericVector Z  = RcppDeepState_NumericVector();
  std::string Z_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/simulate_r/libFuzzer_simulate_r/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_Z.qs";
  qs::c_qsave(Z,Z_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Z values: "<< Z << std::endl;
  NumericVector h0(1);
  h0[0]  = RcppDeepState_double();
  std::string h0_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/simulate_r/libFuzzer_simulate_r/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_h0.qs";
  qs::c_qsave(h0,h0_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "h0 values: "<< h0 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    simulate_r(n_days[0],n_intraday[0],alpha[0],beta[0],gamma[0],Z,h0[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
