// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// Photoperiod_DeepState_TestHarness_generation.cpp and Photoperiod_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector Photoperiod(NumericVector doy, NumericVector latitude);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector doy  = RcppDeepState_NumericVector();
  std::string doy_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/Photoperiod/libFuzzer_Photoperiod/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_doy.qs";
  qs::c_qsave(doy,doy_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "doy values: "<< doy << std::endl;
  NumericVector latitude  = RcppDeepState_NumericVector();
  std::string latitude_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/Photoperiod/libFuzzer_Photoperiod/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_latitude.qs";
  qs::c_qsave(latitude,latitude_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "latitude values: "<< latitude << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    Photoperiod(doy,latitude);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
