// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// getMergeMatrix_DeepState_TestHarness_generation.cpp and getMergeMatrix_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List getMergeMatrix(IntegerVector group, IntegerVector parent, IntegerVector order);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector group  = RcppDeepState_IntegerVector();
  qs::c_qsave(group,"/home/akhila/fuzzer_packages/fuzzedpackages/mergeTrees/inst/testfiles/getMergeMatrix/inputs/group.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "group values: "<< group << std::endl;
  IntegerVector parent  = RcppDeepState_IntegerVector();
  qs::c_qsave(parent,"/home/akhila/fuzzer_packages/fuzzedpackages/mergeTrees/inst/testfiles/getMergeMatrix/inputs/parent.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "parent values: "<< parent << std::endl;
  IntegerVector order  = RcppDeepState_IntegerVector();
  qs::c_qsave(order,"/home/akhila/fuzzer_packages/fuzzedpackages/mergeTrees/inst/testfiles/getMergeMatrix/inputs/order.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "order values: "<< order << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    getMergeMatrix(group,parent,order);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
