// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// duration_from_string_impl_DeepState_TestHarness_generation.cpp and duration_from_string_impl_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericVector duration_from_string_impl(Rcpp::CharacterVector str);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  CharacterVector str  = RcppDeepState_CharacterVector();
  qs::c_qsave(str,"/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/duration_from_string_impl/inputs/str.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "str values: "<< str << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    duration_from_string_impl(str);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
