// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ET0_Makkink_DeepState_TestHarness_generation.cpp and ET0_Makkink_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector ET0_Makkink(NumericVector temp, NumericVector relh, NumericVector atmp, NumericVector Rs);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector temp  = RcppDeepState_NumericVector();
  qs::c_qsave(temp,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_Makkink/inputs/temp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "temp values: "<< temp << std::endl;
  NumericVector relh  = RcppDeepState_NumericVector();
  qs::c_qsave(relh,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_Makkink/inputs/relh.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "relh values: "<< relh << std::endl;
  NumericVector atmp  = RcppDeepState_NumericVector();
  qs::c_qsave(atmp,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_Makkink/inputs/atmp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "atmp values: "<< atmp << std::endl;
  NumericVector Rs  = RcppDeepState_NumericVector();
  qs::c_qsave(Rs,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_Makkink/inputs/Rs.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Rs values: "<< Rs << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ET0_Makkink(temp,relh,atmp,Rs);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
