// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// period_from_integer_impl_DeepState_TestHarness_generation.cpp and period_from_integer_impl_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::ComplexVector period_from_integer_impl(Rcpp::IntegerVector iint);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector iint  = RcppDeepState_IntegerVector();
  std::string iint_t = "/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/period_from_integer_impl/AFL_period_from_integer_impl/afl_inputs/" + std::to_string(t) + "_iint.qs";
  qs::c_qsave(iint,iint_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "iint values: "<< iint << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    period_from_integer_impl(iint);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
