// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// calculate_p_DeepState_TestHarness_generation.cpp and calculate_p_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector calculate_p(double ndays, double delta, double mu, NumericVector Zp, NumericVector h, double p0);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector ndays(1);
  ndays[0]  = RcppDeepState_double();
  std::string ndays_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/calculate_p/libFuzzer_calculate_p/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ndays.qs";
  qs::c_qsave(ndays,ndays_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ndays values: "<< ndays << std::endl;
  NumericVector delta(1);
  delta[0]  = RcppDeepState_double();
  std::string delta_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/calculate_p/libFuzzer_calculate_p/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_delta.qs";
  qs::c_qsave(delta,delta_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "delta values: "<< delta << std::endl;
  NumericVector mu(1);
  mu[0]  = RcppDeepState_double();
  std::string mu_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/calculate_p/libFuzzer_calculate_p/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_mu.qs";
  qs::c_qsave(mu,mu_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mu values: "<< mu << std::endl;
  NumericVector Zp  = RcppDeepState_NumericVector();
  std::string Zp_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/calculate_p/libFuzzer_calculate_p/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_Zp.qs";
  qs::c_qsave(Zp,Zp_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Zp values: "<< Zp << std::endl;
  NumericVector h  = RcppDeepState_NumericVector();
  std::string h_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/calculate_p/libFuzzer_calculate_p/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_h.qs";
  qs::c_qsave(h,h_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "h values: "<< h << std::endl;
  NumericVector p0(1);
  p0[0]  = RcppDeepState_double();
  std::string p0_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/calculate_p/libFuzzer_calculate_p/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_p0.qs";
  qs::c_qsave(p0,p0_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p0 values: "<< p0 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    calculate_p(ndays[0],delta[0],mu[0],Zp,h,p0[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
