// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// Photoperiod_DeepState_TestHarness_generation.cpp and Photoperiod_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector Photoperiod(NumericVector doy, NumericVector latitude);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector doy  = RcppDeepState_NumericVector();
  qs::c_qsave(doy,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/Photoperiod/inputs/doy.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "doy values: "<< doy << std::endl;
  NumericVector latitude  = RcppDeepState_NumericVector();
  qs::c_qsave(latitude,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/Photoperiod/inputs/latitude.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "latitude values: "<< latitude << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    Photoperiod(doy,latitude);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
