// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// hourlyFromDailyRH_DeepState_TestHarness_generation.cpp and hourlyFromDailyRH_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix hourlyFromDailyRH(NumericVector relh, NumericVector tmin, NumericVector tmax, NumericVector doy, NumericVector latitude);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector relh  = RcppDeepState_NumericVector();
  qs::c_qsave(relh,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/hourlyFromDailyRH/inputs/relh.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "relh values: "<< relh << std::endl;
  NumericVector tmin  = RcppDeepState_NumericVector();
  qs::c_qsave(tmin,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/hourlyFromDailyRH/inputs/tmin.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tmin values: "<< tmin << std::endl;
  NumericVector tmax  = RcppDeepState_NumericVector();
  qs::c_qsave(tmax,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/hourlyFromDailyRH/inputs/tmax.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tmax values: "<< tmax << std::endl;
  NumericVector doy  = RcppDeepState_NumericVector();
  qs::c_qsave(doy,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/hourlyFromDailyRH/inputs/doy.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "doy values: "<< doy << std::endl;
  NumericVector latitude  = RcppDeepState_NumericVector();
  qs::c_qsave(latitude,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/hourlyFromDailyRH/inputs/latitude.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "latitude values: "<< latitude << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    hourlyFromDailyRH(relh,tmin,tmax,doy,latitude);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
