// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// calculate_g_DeepState_TestHarness_generation.cpp and calculate_g_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector calculate_g(double omega, double alpha, double beta, double gamma, NumericVector returns, double g0);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector omega(1);
  omega[0]  = RcppDeepState_double();
  qs::c_qsave(omega,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/calculate_g/inputs/omega.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "omega values: "<< omega << std::endl;
  NumericVector alpha(1);
  alpha[0]  = RcppDeepState_double();
  qs::c_qsave(alpha,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/calculate_g/inputs/alpha.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "alpha values: "<< alpha << std::endl;
  NumericVector beta(1);
  beta[0]  = RcppDeepState_double();
  qs::c_qsave(beta,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/calculate_g/inputs/beta.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "beta values: "<< beta << std::endl;
  NumericVector gamma(1);
  gamma[0]  = RcppDeepState_double();
  qs::c_qsave(gamma,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/calculate_g/inputs/gamma.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "gamma values: "<< gamma << std::endl;
  NumericVector returns  = RcppDeepState_NumericVector();
  qs::c_qsave(returns,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/calculate_g/inputs/returns.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "returns values: "<< returns << std::endl;
  NumericVector g0(1);
  g0[0]  = RcppDeepState_double();
  qs::c_qsave(g0,"/home/akhila/fuzzer_packages/fuzzedpackages/mfGARCH/inst/testfiles/calculate_g/inputs/g0.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "g0 values: "<< g0 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    calculate_g(omega[0],alpha[0],beta[0],gamma[0],returns,g0[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
