// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// getcommsize_DeepState_TestHarness_generation.cpp and getcommsize_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector getcommsize(NumericVector x, NumericVector ux);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/mclustcomp/inst/testfiles/getcommsize/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector ux  = RcppDeepState_NumericVector();
  qs::c_qsave(ux,"/home/akhila/fuzzer_packages/fuzzedpackages/mclustcomp/inst/testfiles/getcommsize/inputs/ux.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ux values: "<< ux << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    getcommsize(x,ux);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
