// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ET0_PriestleyTaylor_DeepState_TestHarness_generation.cpp and ET0_PriestleyTaylor_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector ET0_PriestleyTaylor(NumericVector temp, NumericVector relh, NumericVector atmp, NumericVector Rn, NumericVector G);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector temp  = RcppDeepState_NumericVector();
  qs::c_qsave(temp,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PriestleyTaylor/inputs/temp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "temp values: "<< temp << std::endl;
  NumericVector relh  = RcppDeepState_NumericVector();
  qs::c_qsave(relh,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PriestleyTaylor/inputs/relh.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "relh values: "<< relh << std::endl;
  NumericVector atmp  = RcppDeepState_NumericVector();
  qs::c_qsave(atmp,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PriestleyTaylor/inputs/atmp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "atmp values: "<< atmp << std::endl;
  NumericVector Rn  = RcppDeepState_NumericVector();
  qs::c_qsave(Rn,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PriestleyTaylor/inputs/Rn.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Rn values: "<< Rn << std::endl;
  NumericVector G  = RcppDeepState_NumericVector();
  qs::c_qsave(G,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PriestleyTaylor/inputs/G.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "G values: "<< G << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ET0_PriestleyTaylor(temp,relh,atmp,Rn,G);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
