// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// est_beta_params_DeepState_TestHarness_generation.cpp and est_beta_params_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector est_beta_params(double mu, double var);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector mu(1);
  mu[0]  = RcppDeepState_double();
  std::string mu_t = "/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/est_beta_params/libFuzzer_est_beta_params/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_mu.qs";
  qs::c_qsave(mu,mu_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mu values: "<< mu << std::endl;
  NumericVector var(1);
  var[0]  = RcppDeepState_double();
  std::string var_t = "/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/est_beta_params/libFuzzer_est_beta_params/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_var.qs";
  qs::c_qsave(var,var_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "var values: "<< var << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    est_beta_params(mu[0],var[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
