// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// UniformCrossOver_DeepState_TestHarness_generation.cpp and UniformCrossOver_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List UniformCrossOver(IntegerVector bytes1, IntegerVector bytes2);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector bytes1  = RcppDeepState_IntegerVector();
  std::string bytes1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mcga/inst/testfiles/UniformCrossOver/AFL_UniformCrossOver/afl_inputs/" + std::to_string(t) + "_bytes1.qs";
  qs::c_qsave(bytes1,bytes1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "bytes1 values: "<< bytes1 << std::endl;
  IntegerVector bytes2  = RcppDeepState_IntegerVector();
  std::string bytes2_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mcga/inst/testfiles/UniformCrossOver/AFL_UniformCrossOver/afl_inputs/" + std::to_string(t) + "_bytes2.qs";
  qs::c_qsave(bytes2,bytes2_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "bytes2 values: "<< bytes2 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    UniformCrossOver(bytes1,bytes2);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
