// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// make_duration_impl_DeepState_TestHarness_generation.cpp and make_duration_impl_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericVector make_duration_impl(const Rcpp::NumericVector h_nv, const Rcpp::NumericVector m_nv, const Rcpp::NumericVector s_nv, const Rcpp::NumericVector n_nv);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector h_nv  = RcppDeepState_NumericVector();
  qs::c_qsave(h_nv,"/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/make_duration_impl/inputs/h_nv.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "h_nv values: "<< h_nv << std::endl;
  NumericVector m_nv  = RcppDeepState_NumericVector();
  qs::c_qsave(m_nv,"/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/make_duration_impl/inputs/m_nv.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "m_nv values: "<< m_nv << std::endl;
  NumericVector s_nv  = RcppDeepState_NumericVector();
  qs::c_qsave(s_nv,"/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/make_duration_impl/inputs/s_nv.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "s_nv values: "<< s_nv << std::endl;
  NumericVector n_nv  = RcppDeepState_NumericVector();
  qs::c_qsave(n_nv,"/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/make_duration_impl/inputs/n_nv.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n_nv values: "<< n_nv << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    make_duration_impl(h_nv,m_nv,s_nv,n_nv);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
