// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// nanoival_make_impl_DeepState_TestHarness_generation.cpp and nanoival_make_impl_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::ComplexVector nanoival_make_impl(const Rcpp::CharacterVector nt_v, const Rcpp::CharacterVector tz_v);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  CharacterVector nt_v  = RcppDeepState_CharacterVector();
  std::string nt_v_t = "/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/nanoival_make_impl/libFuzzer_nanoival_make_impl/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nt_v.qs";
  qs::c_qsave(nt_v,nt_v_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nt_v values: "<< nt_v << std::endl;
  CharacterVector tz_v  = RcppDeepState_CharacterVector();
  std::string tz_v_t = "/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/nanoival_make_impl/libFuzzer_nanoival_make_impl/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tz_v.qs";
  qs::c_qsave(tz_v,tz_v_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tz_v values: "<< tz_v << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    nanoival_make_impl(nt_v,tz_v);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
