// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// calculate_mutual_information_DeepState_TestHarness_generation.cpp and calculate_mutual_information_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector calculate_mutual_information(const NumericVector& tseries, const int& maxlag, const int& nPartitions);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector tseries  = RcppDeepState_NumericVector();
  std::string tseries_t = "/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/calculate_mutual_information/libFuzzer_calculate_mutual_information/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tseries.qs";
  qs::c_qsave(tseries,tseries_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tseries values: "<< tseries << std::endl;
  IntegerVector maxlag(1);
  maxlag[0]  = RcppDeepState_int();
  std::string maxlag_t = "/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/calculate_mutual_information/libFuzzer_calculate_mutual_information/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_maxlag.qs";
  qs::c_qsave(maxlag,maxlag_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "maxlag values: "<< maxlag << std::endl;
  IntegerVector nPartitions(1);
  nPartitions[0]  = RcppDeepState_int();
  std::string nPartitions_t = "/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/calculate_mutual_information/libFuzzer_calculate_mutual_information/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nPartitions.qs";
  qs::c_qsave(nPartitions,nPartitions_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nPartitions values: "<< nPartitions << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    calculate_mutual_information(tseries,maxlag[0],nPartitions[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
