// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// fastlm_DeepState_TestHarness_generation.cpp and fastlm_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::colvec fastlm(NumericVector yr, NumericMatrix Xr);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector yr  = RcppDeepState_NumericVector();
  qs::c_qsave(yr,"/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/fastlm/inputs/yr.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "yr values: "<< yr << std::endl;
  NumericMatrix Xr  = RcppDeepState_NumericMatrix();
  qs::c_qsave(Xr,"/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/fastlm/inputs/Xr.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Xr values: "<< Xr << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    fastlm(yr,Xr);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
