// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// impl_error_DeepState_TestHarness_generation.cpp and impl_error_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector impl_error(NumericVector mu, double sigma_impl);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector mu  = RcppDeepState_NumericVector();
  qs::c_qsave(mu,"/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/impl_error/inputs/mu.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mu values: "<< mu << std::endl;
  NumericVector sigma_impl(1);
  sigma_impl[0]  = RcppDeepState_double();
  qs::c_qsave(sigma_impl,"/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/impl_error/inputs/sigma_impl.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "sigma_impl values: "<< sigma_impl << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    impl_error(mu,sigma_impl[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
