// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cpp_TAI_DeepState_TestHarness_generation.cpp and cpp_TAI_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector cpp_TAI(const NumericMatrix& ExpressionSet, const NumericVector& Phylostratum);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix ExpressionSet  = RcppDeepState_NumericMatrix();
  qs::c_qsave(ExpressionSet,"/home/akhila/fuzzer_packages/fuzzedpackages/myTAI/inst/testfiles/cpp_TAI/inputs/ExpressionSet.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ExpressionSet values: "<< ExpressionSet << std::endl;
  NumericVector Phylostratum  = RcppDeepState_NumericVector();
  qs::c_qsave(Phylostratum,"/home/akhila/fuzzer_packages/fuzzedpackages/myTAI/inst/testfiles/cpp_TAI/inputs/Phylostratum.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Phylostratum values: "<< Phylostratum << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cpp_TAI(ExpressionSet,Phylostratum);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
