// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// fit_ricker_DeepState_TestHarness_generation.cpp and fit_ricker_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector fit_ricker(NumericVector S, NumericVector R);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector S  = RcppDeepState_NumericVector();
  qs::c_qsave(S,"/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/fit_ricker/inputs/S.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "S values: "<< S << std::endl;
  NumericVector R  = RcppDeepState_NumericVector();
  qs::c_qsave(R,"/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/fit_ricker/inputs/R.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "R values: "<< R << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    fit_ricker(S,R);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
