// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// est_beta_params_DeepState_TestHarness_generation.cpp and est_beta_params_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector est_beta_params(double mu, double var);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector mu(1);
  mu[0]  = RcppDeepState_double();
  qs::c_qsave(mu,"/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/est_beta_params/inputs/mu.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mu values: "<< mu << std::endl;
  NumericVector var(1);
  var[0]  = RcppDeepState_double();
  qs::c_qsave(var,"/home/akhila/fuzzer_packages/fuzzedpackages/metafolio/inst/testfiles/est_beta_params/inputs/var.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "var values: "<< var << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    est_beta_params(mu[0],var[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
