// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// intersect_line_rectangle_DeepState_TestHarness_generation.cpp and intersect_line_rectangle_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector intersect_line_rectangle(NumericVector p1, NumericVector p2, NumericVector b);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector p1  = RcppDeepState_NumericVector();
  std::string p1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/metacoder/inst/testfiles/intersect_line_rectangle/AFL_intersect_line_rectangle/afl_inputs/" + std::to_string(t) + "_p1.qs";
  qs::c_qsave(p1,p1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p1 values: "<< p1 << std::endl;
  NumericVector p2  = RcppDeepState_NumericVector();
  std::string p2_t = "/home/akhila/fuzzer_packages/fuzzedpackages/metacoder/inst/testfiles/intersect_line_rectangle/AFL_intersect_line_rectangle/afl_inputs/" + std::to_string(t) + "_p2.qs";
  qs::c_qsave(p2,p2_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p2 values: "<< p2 << std::endl;
  NumericVector b  = RcppDeepState_NumericVector();
  std::string b_t = "/home/akhila/fuzzer_packages/fuzzedpackages/metacoder/inst/testfiles/intersect_line_rectangle/AFL_intersect_line_rectangle/afl_inputs/" + std::to_string(t) + "_b.qs";
  qs::c_qsave(b,b_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "b values: "<< b << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    intersect_line_rectangle(p1,p2,b);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
