// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// period_from_parts_impl_DeepState_TestHarness_generation.cpp and period_from_parts_impl_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::ComplexVector period_from_parts_impl(Rcpp::IntegerVector months_v, Rcpp::IntegerVector days_v, Rcpp::NumericVector dur_v);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector months_v  = RcppDeepState_IntegerVector();
  qs::c_qsave(months_v,"/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/period_from_parts_impl/inputs/months_v.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "months_v values: "<< months_v << std::endl;
  IntegerVector days_v  = RcppDeepState_IntegerVector();
  qs::c_qsave(days_v,"/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/period_from_parts_impl/inputs/days_v.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "days_v values: "<< days_v << std::endl;
  NumericVector dur_v  = RcppDeepState_NumericVector();
  qs::c_qsave(dur_v,"/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/period_from_parts_impl/inputs/dur_v.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dur_v values: "<< dur_v << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    period_from_parts_impl(months_v,days_v,dur_v);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
