// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// calculate_fluctuation_function_DeepState_TestHarness_generation.cpp and calculate_fluctuation_function_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector calculate_fluctuation_function(NumericVector& yr, NumericVector& windowSizesVector);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector yr  = RcppDeepState_NumericVector();
  qs::c_qsave(yr,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/calculate_fluctuation_function/inputs/yr.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "yr values: "<< yr << std::endl;
  NumericVector windowSizesVector  = RcppDeepState_NumericVector();
  qs::c_qsave(windowSizesVector,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/calculate_fluctuation_function/inputs/windowSizesVector.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "windowSizesVector values: "<< windowSizesVector << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    calculate_fluctuation_function(yr,windowSizesVector);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
