// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// MaxDouble
double MaxDouble();
RcppExport SEXP _mcga_MaxDouble() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(MaxDouble());
    return rcpp_result_gen;
END_RCPP
}
// SizeOfDouble
int SizeOfDouble();
RcppExport SEXP _mcga_SizeOfDouble() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(SizeOfDouble());
    return rcpp_result_gen;
END_RCPP
}
// SizeOfInt
int SizeOfInt();
RcppExport SEXP _mcga_SizeOfInt() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(SizeOfInt());
    return rcpp_result_gen;
END_RCPP
}
// SizeOfLong
int SizeOfLong();
RcppExport SEXP _mcga_SizeOfLong() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(SizeOfLong());
    return rcpp_result_gen;
END_RCPP
}
// DoubleToBytes
IntegerVector DoubleToBytes(double x);
RcppExport SEXP _mcga_DoubleToBytes(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(DoubleToBytes(x));
    return rcpp_result_gen;
END_RCPP
}
// DoubleVectorToBytes
IntegerVector DoubleVectorToBytes(DoubleVector d);
RcppExport SEXP _mcga_DoubleVectorToBytes(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DoubleVector >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DoubleVectorToBytes(d));
    return rcpp_result_gen;
END_RCPP
}
// BytesToDouble
double BytesToDouble(IntegerVector x);
RcppExport SEXP _mcga_BytesToDouble(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(BytesToDouble(x));
    return rcpp_result_gen;
END_RCPP
}
// ByteVectorToDoubles
DoubleVector ByteVectorToDoubles(IntegerVector b);
RcppExport SEXP _mcga_ByteVectorToDoubles(SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(ByteVectorToDoubles(b));
    return rcpp_result_gen;
END_RCPP
}
// OnePointCrossOver
List OnePointCrossOver(IntegerVector bytes1, IntegerVector bytes2, unsigned int cutpoint);
RcppExport SEXP _mcga_OnePointCrossOver(SEXP bytes1SEXP, SEXP bytes2SEXP, SEXP cutpointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type bytes1(bytes1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type bytes2(bytes2SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type cutpoint(cutpointSEXP);
    rcpp_result_gen = Rcpp::wrap(OnePointCrossOver(bytes1, bytes2, cutpoint));
    return rcpp_result_gen;
END_RCPP
}
// OnePointCrossOverOnDoublesUsingBytes
List OnePointCrossOverOnDoublesUsingBytes(DoubleVector d1, DoubleVector d2, unsigned int cutpoint);
RcppExport SEXP _mcga_OnePointCrossOverOnDoublesUsingBytes(SEXP d1SEXP, SEXP d2SEXP, SEXP cutpointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DoubleVector >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type cutpoint(cutpointSEXP);
    rcpp_result_gen = Rcpp::wrap(OnePointCrossOverOnDoublesUsingBytes(d1, d2, cutpoint));
    return rcpp_result_gen;
END_RCPP
}
// TwoPointCrossOver
List TwoPointCrossOver(IntegerVector bytes1, IntegerVector bytes2, unsigned int cutpoint1, unsigned int cutpoint2);
RcppExport SEXP _mcga_TwoPointCrossOver(SEXP bytes1SEXP, SEXP bytes2SEXP, SEXP cutpoint1SEXP, SEXP cutpoint2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type bytes1(bytes1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type bytes2(bytes2SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type cutpoint1(cutpoint1SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type cutpoint2(cutpoint2SEXP);
    rcpp_result_gen = Rcpp::wrap(TwoPointCrossOver(bytes1, bytes2, cutpoint1, cutpoint2));
    return rcpp_result_gen;
END_RCPP
}
// TwoPointCrossOverOnDoublesUsingBytes
List TwoPointCrossOverOnDoublesUsingBytes(DoubleVector d1, DoubleVector d2, unsigned int cutpoint1, unsigned int cutpoint2);
RcppExport SEXP _mcga_TwoPointCrossOverOnDoublesUsingBytes(SEXP d1SEXP, SEXP d2SEXP, SEXP cutpoint1SEXP, SEXP cutpoint2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DoubleVector >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type cutpoint1(cutpoint1SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type cutpoint2(cutpoint2SEXP);
    rcpp_result_gen = Rcpp::wrap(TwoPointCrossOverOnDoublesUsingBytes(d1, d2, cutpoint1, cutpoint2));
    return rcpp_result_gen;
END_RCPP
}
// UniformCrossOver
List UniformCrossOver(IntegerVector bytes1, IntegerVector bytes2);
RcppExport SEXP _mcga_UniformCrossOver(SEXP bytes1SEXP, SEXP bytes2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type bytes1(bytes1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type bytes2(bytes2SEXP);
    rcpp_result_gen = Rcpp::wrap(UniformCrossOver(bytes1, bytes2));
    return rcpp_result_gen;
END_RCPP
}
// UniformCrossOverOnDoublesUsingBytes
List UniformCrossOverOnDoublesUsingBytes(DoubleVector d1, DoubleVector d2);
RcppExport SEXP _mcga_UniformCrossOverOnDoublesUsingBytes(SEXP d1SEXP, SEXP d2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DoubleVector >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type d2(d2SEXP);
    rcpp_result_gen = Rcpp::wrap(UniformCrossOverOnDoublesUsingBytes(d1, d2));
    return rcpp_result_gen;
END_RCPP
}
// ByteCodeMutation
IntegerVector ByteCodeMutation(IntegerVector bytes1, const double pmutation);
RcppExport SEXP _mcga_ByteCodeMutation(SEXP bytes1SEXP, SEXP pmutationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type bytes1(bytes1SEXP);
    Rcpp::traits::input_parameter< const double >::type pmutation(pmutationSEXP);
    rcpp_result_gen = Rcpp::wrap(ByteCodeMutation(bytes1, pmutation));
    return rcpp_result_gen;
END_RCPP
}
// ByteCodeMutationUsingDoubles
DoubleVector ByteCodeMutationUsingDoubles(DoubleVector d, const double pmutation);
RcppExport SEXP _mcga_ByteCodeMutationUsingDoubles(SEXP dSEXP, SEXP pmutationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DoubleVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< const double >::type pmutation(pmutationSEXP);
    rcpp_result_gen = Rcpp::wrap(ByteCodeMutationUsingDoubles(d, pmutation));
    return rcpp_result_gen;
END_RCPP
}
// ByteCodeMutationUsingDoublesRandom
DoubleVector ByteCodeMutationUsingDoublesRandom(DoubleVector d, const double pmutation);
RcppExport SEXP _mcga_ByteCodeMutationUsingDoublesRandom(SEXP dSEXP, SEXP pmutationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DoubleVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< const double >::type pmutation(pmutationSEXP);
    rcpp_result_gen = Rcpp::wrap(ByteCodeMutationUsingDoublesRandom(d, pmutation));
    return rcpp_result_gen;
END_RCPP
}
// EnsureBounds
void EnsureBounds(DoubleVector doubles, DoubleVector mins, DoubleVector maxs);
RcppExport SEXP _mcga_EnsureBounds(SEXP doublesSEXP, SEXP minsSEXP, SEXP maxsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DoubleVector >::type doubles(doublesSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type mins(minsSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type maxs(maxsSEXP);
    EnsureBounds(doubles, mins, maxs);
    return R_NilValue;
END_RCPP
}

RcppExport SEXP mcga(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP multi_mcga(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_mcga_MaxDouble", (DL_FUNC) &_mcga_MaxDouble, 0},
    {"_mcga_SizeOfDouble", (DL_FUNC) &_mcga_SizeOfDouble, 0},
    {"_mcga_SizeOfInt", (DL_FUNC) &_mcga_SizeOfInt, 0},
    {"_mcga_SizeOfLong", (DL_FUNC) &_mcga_SizeOfLong, 0},
    {"_mcga_DoubleToBytes", (DL_FUNC) &_mcga_DoubleToBytes, 1},
    {"_mcga_DoubleVectorToBytes", (DL_FUNC) &_mcga_DoubleVectorToBytes, 1},
    {"_mcga_BytesToDouble", (DL_FUNC) &_mcga_BytesToDouble, 1},
    {"_mcga_ByteVectorToDoubles", (DL_FUNC) &_mcga_ByteVectorToDoubles, 1},
    {"_mcga_OnePointCrossOver", (DL_FUNC) &_mcga_OnePointCrossOver, 3},
    {"_mcga_OnePointCrossOverOnDoublesUsingBytes", (DL_FUNC) &_mcga_OnePointCrossOverOnDoublesUsingBytes, 3},
    {"_mcga_TwoPointCrossOver", (DL_FUNC) &_mcga_TwoPointCrossOver, 4},
    {"_mcga_TwoPointCrossOverOnDoublesUsingBytes", (DL_FUNC) &_mcga_TwoPointCrossOverOnDoublesUsingBytes, 4},
    {"_mcga_UniformCrossOver", (DL_FUNC) &_mcga_UniformCrossOver, 2},
    {"_mcga_UniformCrossOverOnDoublesUsingBytes", (DL_FUNC) &_mcga_UniformCrossOverOnDoublesUsingBytes, 2},
    {"_mcga_ByteCodeMutation", (DL_FUNC) &_mcga_ByteCodeMutation, 2},
    {"_mcga_ByteCodeMutationUsingDoubles", (DL_FUNC) &_mcga_ByteCodeMutationUsingDoubles, 2},
    {"_mcga_ByteCodeMutationUsingDoublesRandom", (DL_FUNC) &_mcga_ByteCodeMutationUsingDoublesRandom, 2},
    {"_mcga_EnsureBounds", (DL_FUNC) &_mcga_EnsureBounds, 3},
    {"mcga",       (DL_FUNC) &mcga,       14},
    {"multi_mcga", (DL_FUNC) &multi_mcga, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_mcga(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
