// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cpp_bootMatrix_DeepState_TestHarness_generation.cpp and cpp_bootMatrix_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix cpp_bootMatrix(const NumericMatrix& ExpressionMatrix, const NumericVector& AgeVector, const int& permutations);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix ExpressionMatrix  = RcppDeepState_NumericMatrix();
  qs::c_qsave(ExpressionMatrix,"/home/akhila/fuzzer_packages/fuzzedpackages/myTAI/inst/testfiles/cpp_bootMatrix/inputs/ExpressionMatrix.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ExpressionMatrix values: "<< ExpressionMatrix << std::endl;
  NumericVector AgeVector  = RcppDeepState_NumericVector();
  qs::c_qsave(AgeVector,"/home/akhila/fuzzer_packages/fuzzedpackages/myTAI/inst/testfiles/cpp_bootMatrix/inputs/AgeVector.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "AgeVector values: "<< AgeVector << std::endl;
  IntegerVector permutations(1);
  permutations[0]  = RcppDeepState_int();
  qs::c_qsave(permutations,"/home/akhila/fuzzer_packages/fuzzedpackages/myTAI/inst/testfiles/cpp_bootMatrix/inputs/permutations.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "permutations values: "<< permutations << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cpp_bootMatrix(ExpressionMatrix,AgeVector,permutations[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
