# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MaxDouble <- function() {
    .Call('_mcga_MaxDouble', PACKAGE = 'mcga')
}

SizeOfDouble <- function() {
    .Call('_mcga_SizeOfDouble', PACKAGE = 'mcga')
}

SizeOfInt <- function() {
    .Call('_mcga_SizeOfInt', PACKAGE = 'mcga')
}

SizeOfLong <- function() {
    .Call('_mcga_SizeOfLong', PACKAGE = 'mcga')
}

DoubleToBytes <- function(x) {
    .Call('_mcga_DoubleToBytes', PACKAGE = 'mcga', x)
}

DoubleVectorToBytes <- function(d) {
    .Call('_mcga_DoubleVectorToBytes', PACKAGE = 'mcga', d)
}

BytesToDouble <- function(x) {
    .Call('_mcga_BytesToDouble', PACKAGE = 'mcga', x)
}

ByteVectorToDoubles <- function(b) {
    .Call('_mcga_ByteVectorToDoubles', PACKAGE = 'mcga', b)
}

OnePointCrossOver <- function(bytes1, bytes2, cutpoint) {
    .Call('_mcga_OnePointCrossOver', PACKAGE = 'mcga', bytes1, bytes2, cutpoint)
}

OnePointCrossOverOnDoublesUsingBytes <- function(d1, d2, cutpoint) {
    .Call('_mcga_OnePointCrossOverOnDoublesUsingBytes', PACKAGE = 'mcga', d1, d2, cutpoint)
}

TwoPointCrossOver <- function(bytes1, bytes2, cutpoint1, cutpoint2) {
    .Call('_mcga_TwoPointCrossOver', PACKAGE = 'mcga', bytes1, bytes2, cutpoint1, cutpoint2)
}

TwoPointCrossOverOnDoublesUsingBytes <- function(d1, d2, cutpoint1, cutpoint2) {
    .Call('_mcga_TwoPointCrossOverOnDoublesUsingBytes', PACKAGE = 'mcga', d1, d2, cutpoint1, cutpoint2)
}

UniformCrossOver <- function(bytes1, bytes2) {
    .Call('_mcga_UniformCrossOver', PACKAGE = 'mcga', bytes1, bytes2)
}

UniformCrossOverOnDoublesUsingBytes <- function(d1, d2) {
    .Call('_mcga_UniformCrossOverOnDoublesUsingBytes', PACKAGE = 'mcga', d1, d2)
}

ByteCodeMutation <- function(bytes1, pmutation) {
    .Call('_mcga_ByteCodeMutation', PACKAGE = 'mcga', bytes1, pmutation)
}

ByteCodeMutationUsingDoubles <- function(d, pmutation) {
    .Call('_mcga_ByteCodeMutationUsingDoubles', PACKAGE = 'mcga', d, pmutation)
}

ByteCodeMutationUsingDoublesRandom <- function(d, pmutation) {
    .Call('_mcga_ByteCodeMutationUsingDoublesRandom', PACKAGE = 'mcga', d, pmutation)
}

EnsureBounds <- function(doubles, mins, maxs) {
    invisible(.Call('_mcga_EnsureBounds', PACKAGE = 'mcga', doubles, mins, maxs))
}

