// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// indexToGridCpp_DeepState_TestHarness_generation.cpp and indexToGridCpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix indexToGridCpp(IntegerVector idx, IntegerVector array_dim);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector idx  = RcppDeepState_IntegerVector();
  qs::c_qsave(idx,"/home/akhila/fuzzer_packages/fuzzedpackages/neuroim/inst/testfiles/indexToGridCpp/inputs/idx.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "idx values: "<< idx << std::endl;
  IntegerVector array_dim  = RcppDeepState_IntegerVector();
  qs::c_qsave(array_dim,"/home/akhila/fuzzer_packages/fuzzedpackages/neuroim/inst/testfiles/indexToGridCpp/inputs/array_dim.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "array_dim values: "<< array_dim << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    indexToGridCpp(idx,array_dim);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
