// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// nanotime_wday_impl_DeepState_TestHarness_generation.cpp and nanotime_wday_impl_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::IntegerVector nanotime_wday_impl(const Rcpp::NumericVector tm_v, const Rcpp::CharacterVector tz_v);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector tm_v  = RcppDeepState_NumericVector();
  std::string tm_v_t = "/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/nanotime_wday_impl/AFL_nanotime_wday_impl/afl_inputs/" + std::to_string(t) + "_tm_v.qs";
  qs::c_qsave(tm_v,tm_v_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tm_v values: "<< tm_v << std::endl;
  CharacterVector tz_v  = RcppDeepState_CharacterVector();
  std::string tz_v_t = "/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/nanotime_wday_impl/AFL_nanotime_wday_impl/afl_inputs/" + std::to_string(t) + "_tz_v.qs";
  qs::c_qsave(tz_v,tz_v_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tz_v values: "<< tz_v << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    nanotime_wday_impl(tm_v,tz_v);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
