// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rcpp_information_dimension_DeepState_TestHarness_generation.cpp and rcpp_information_dimension_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix rcpp_information_dimension(const NumericVector& timeSeries, const IntegerVector& embeddingDimensions, int timeLag, const NumericVector& fixedMasses, double radius, double increasingRadiusFactor, int nBoxes, int nReferenceVectors, int theilerWindow, int nNeighbours);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector timeSeries  = RcppDeepState_NumericVector();
  qs::c_qsave(timeSeries,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/rcpp_information_dimension/inputs/timeSeries.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "timeSeries values: "<< timeSeries << std::endl;
  IntegerVector embeddingDimensions  = RcppDeepState_IntegerVector();
  qs::c_qsave(embeddingDimensions,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/rcpp_information_dimension/inputs/embeddingDimensions.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "embeddingDimensions values: "<< embeddingDimensions << std::endl;
  IntegerVector timeLag(1);
  timeLag[0]  = RcppDeepState_int();
  qs::c_qsave(timeLag,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/rcpp_information_dimension/inputs/timeLag.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "timeLag values: "<< timeLag << std::endl;
  NumericVector fixedMasses  = RcppDeepState_NumericVector();
  qs::c_qsave(fixedMasses,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/rcpp_information_dimension/inputs/fixedMasses.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "fixedMasses values: "<< fixedMasses << std::endl;
  NumericVector radius(1);
  radius[0]  = RcppDeepState_double();
  qs::c_qsave(radius,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/rcpp_information_dimension/inputs/radius.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "radius values: "<< radius << std::endl;
  NumericVector increasingRadiusFactor(1);
  increasingRadiusFactor[0]  = RcppDeepState_double();
  qs::c_qsave(increasingRadiusFactor,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/rcpp_information_dimension/inputs/increasingRadiusFactor.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "increasingRadiusFactor values: "<< increasingRadiusFactor << std::endl;
  IntegerVector nBoxes(1);
  nBoxes[0]  = RcppDeepState_int();
  qs::c_qsave(nBoxes,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/rcpp_information_dimension/inputs/nBoxes.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nBoxes values: "<< nBoxes << std::endl;
  IntegerVector nReferenceVectors(1);
  nReferenceVectors[0]  = RcppDeepState_int();
  qs::c_qsave(nReferenceVectors,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/rcpp_information_dimension/inputs/nReferenceVectors.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nReferenceVectors values: "<< nReferenceVectors << std::endl;
  IntegerVector theilerWindow(1);
  theilerWindow[0]  = RcppDeepState_int();
  qs::c_qsave(theilerWindow,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/rcpp_information_dimension/inputs/theilerWindow.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "theilerWindow values: "<< theilerWindow << std::endl;
  IntegerVector nNeighbours(1);
  nNeighbours[0]  = RcppDeepState_int();
  qs::c_qsave(nNeighbours,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/rcpp_information_dimension/inputs/nNeighbours.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nNeighbours values: "<< nNeighbours << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rcpp_information_dimension(timeSeries,embeddingDimensions,timeLag[0],fixedMasses,radius[0],increasingRadiusFactor[0],nBoxes[0],nReferenceVectors[0],theilerWindow[0],nNeighbours[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
