// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ET0_PenmanMonteith_DeepState_TestHarness_generation.cpp and ET0_PenmanMonteith_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector ET0_PenmanMonteith(NumericVector temp, NumericVector relh, NumericVector atmp, NumericVector Rn, NumericVector G, NumericVector ra, NumericVector rs);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector temp  = RcppDeepState_NumericVector();
  std::string temp_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PenmanMonteith/AFL_ET0_PenmanMonteith/afl_inputs/" + std::to_string(t) + "_temp.qs";
  qs::c_qsave(temp,temp_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "temp values: "<< temp << std::endl;
  NumericVector relh  = RcppDeepState_NumericVector();
  std::string relh_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PenmanMonteith/AFL_ET0_PenmanMonteith/afl_inputs/" + std::to_string(t) + "_relh.qs";
  qs::c_qsave(relh,relh_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "relh values: "<< relh << std::endl;
  NumericVector atmp  = RcppDeepState_NumericVector();
  std::string atmp_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PenmanMonteith/AFL_ET0_PenmanMonteith/afl_inputs/" + std::to_string(t) + "_atmp.qs";
  qs::c_qsave(atmp,atmp_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "atmp values: "<< atmp << std::endl;
  NumericVector Rn  = RcppDeepState_NumericVector();
  std::string Rn_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PenmanMonteith/AFL_ET0_PenmanMonteith/afl_inputs/" + std::to_string(t) + "_Rn.qs";
  qs::c_qsave(Rn,Rn_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Rn values: "<< Rn << std::endl;
  NumericVector G  = RcppDeepState_NumericVector();
  std::string G_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PenmanMonteith/AFL_ET0_PenmanMonteith/afl_inputs/" + std::to_string(t) + "_G.qs";
  qs::c_qsave(G,G_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "G values: "<< G << std::endl;
  NumericVector ra  = RcppDeepState_NumericVector();
  std::string ra_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PenmanMonteith/AFL_ET0_PenmanMonteith/afl_inputs/" + std::to_string(t) + "_ra.qs";
  qs::c_qsave(ra,ra_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ra values: "<< ra << std::endl;
  NumericVector rs  = RcppDeepState_NumericVector();
  std::string rs_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PenmanMonteith/AFL_ET0_PenmanMonteith/afl_inputs/" + std::to_string(t) + "_rs.qs";
  qs::c_qsave(rs,rs_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rs values: "<< rs << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ET0_PenmanMonteith(temp,relh,atmp,Rn,G,ra,rs);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
