// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cpp_pMatrix_DeepState_TestHarness_generation.cpp and cpp_pMatrix_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix cpp_pMatrix(const NumericMatrix& ExpressionSet, const NumericVector& AgeVector);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix ExpressionSet  = RcppDeepState_NumericMatrix();
  std::string ExpressionSet_t = "/home/akhila/fuzzer_packages/fuzzedpackages/myTAI/inst/testfiles/cpp_pMatrix/libFuzzer_cpp_pMatrix/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ExpressionSet.qs";
  qs::c_qsave(ExpressionSet,ExpressionSet_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ExpressionSet values: "<< ExpressionSet << std::endl;
  NumericVector AgeVector  = RcppDeepState_NumericVector();
  std::string AgeVector_t = "/home/akhila/fuzzer_packages/fuzzedpackages/myTAI/inst/testfiles/cpp_pMatrix/libFuzzer_cpp_pMatrix/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_AgeVector.qs";
  qs::c_qsave(AgeVector,AgeVector_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "AgeVector values: "<< AgeVector << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cpp_pMatrix(ExpressionSet,AgeVector);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
