// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// nanotime_year_impl_DeepState_TestHarness_generation.cpp and nanotime_year_impl_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::IntegerVector nanotime_year_impl(const Rcpp::NumericVector tm_v, const Rcpp::CharacterVector tz_v);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector tm_v  = RcppDeepState_NumericVector();
  qs::c_qsave(tm_v,"/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/nanotime_year_impl/inputs/tm_v.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tm_v values: "<< tm_v << std::endl;
  CharacterVector tz_v  = RcppDeepState_CharacterVector();
  qs::c_qsave(tz_v,"/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/nanotime_year_impl/inputs/tz_v.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tz_v values: "<< tz_v << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    nanotime_year_impl(tm_v,tz_v);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
