// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// gridToIndex3DCpp_DeepState_TestHarness_generation.cpp and gridToIndex3DCpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector gridToIndex3DCpp(IntegerVector array_dim, NumericMatrix voxmat);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector array_dim  = RcppDeepState_IntegerVector();
  qs::c_qsave(array_dim,"/home/akhila/fuzzer_packages/fuzzedpackages/neuroim/inst/testfiles/gridToIndex3DCpp/inputs/array_dim.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "array_dim values: "<< array_dim << std::endl;
  NumericMatrix voxmat  = RcppDeepState_NumericMatrix();
  qs::c_qsave(voxmat,"/home/akhila/fuzzer_packages/fuzzedpackages/neuroim/inst/testfiles/gridToIndex3DCpp/inputs/voxmat.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "voxmat values: "<< voxmat << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    gridToIndex3DCpp(array_dim,voxmat);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
