// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// getprobs_DeepState_TestHarness_generation.cpp and getprobs_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List getprobs(NumericMatrix confmat, NumericVector scx, NumericVector scy, const int n, double threps);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix confmat  = RcppDeepState_NumericMatrix();
  qs::c_qsave(confmat,"/home/akhila/fuzzer_packages/fuzzedpackages/mclustcomp/inst/testfiles/getprobs/inputs/confmat.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "confmat values: "<< confmat << std::endl;
  NumericVector scx  = RcppDeepState_NumericVector();
  qs::c_qsave(scx,"/home/akhila/fuzzer_packages/fuzzedpackages/mclustcomp/inst/testfiles/getprobs/inputs/scx.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "scx values: "<< scx << std::endl;
  NumericVector scy  = RcppDeepState_NumericVector();
  qs::c_qsave(scy,"/home/akhila/fuzzer_packages/fuzzedpackages/mclustcomp/inst/testfiles/getprobs/inputs/scy.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "scy values: "<< scy << std::endl;
  IntegerVector n(1);
  n[0]  = RcppDeepState_int();
  qs::c_qsave(n,"/home/akhila/fuzzer_packages/fuzzedpackages/mclustcomp/inst/testfiles/getprobs/inputs/n.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  NumericVector threps(1);
  threps[0]  = RcppDeepState_double();
  qs::c_qsave(threps,"/home/akhila/fuzzer_packages/fuzzedpackages/mclustcomp/inst/testfiles/getprobs/inputs/threps.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "threps values: "<< threps << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    getprobs(confmat,scx,scy,n[0],threps[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
