// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ET0_PenmanMonteith_DeepState_TestHarness_generation.cpp and ET0_PenmanMonteith_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector ET0_PenmanMonteith(NumericVector temp, NumericVector relh, NumericVector atmp, NumericVector Rn, NumericVector G, NumericVector ra, NumericVector rs);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector temp  = RcppDeepState_NumericVector();
  qs::c_qsave(temp,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PenmanMonteith/inputs/temp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "temp values: "<< temp << std::endl;
  NumericVector relh  = RcppDeepState_NumericVector();
  qs::c_qsave(relh,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PenmanMonteith/inputs/relh.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "relh values: "<< relh << std::endl;
  NumericVector atmp  = RcppDeepState_NumericVector();
  qs::c_qsave(atmp,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PenmanMonteith/inputs/atmp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "atmp values: "<< atmp << std::endl;
  NumericVector Rn  = RcppDeepState_NumericVector();
  qs::c_qsave(Rn,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PenmanMonteith/inputs/Rn.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Rn values: "<< Rn << std::endl;
  NumericVector G  = RcppDeepState_NumericVector();
  qs::c_qsave(G,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PenmanMonteith/inputs/G.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "G values: "<< G << std::endl;
  NumericVector ra  = RcppDeepState_NumericVector();
  qs::c_qsave(ra,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PenmanMonteith/inputs/ra.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ra values: "<< ra << std::endl;
  NumericVector rs  = RcppDeepState_NumericVector();
  qs::c_qsave(rs,"/home/akhila/fuzzer_packages/fuzzedpackages/meteor/inst/testfiles/ET0_PenmanMonteith/inputs/rs.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rs values: "<< rs << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ET0_PenmanMonteith(temp,relh,atmp,Rn,G,ra,rs);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
