// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// nonlinear_noise_reduction_DeepState_TestHarness_generation.cpp and nonlinear_noise_reduction_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector nonlinear_noise_reduction(const NumericVector& timeSeries, int embeddingDimension, double radius, int nBoxes);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector timeSeries  = RcppDeepState_NumericVector();
  qs::c_qsave(timeSeries,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/nonlinear_noise_reduction/inputs/timeSeries.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "timeSeries values: "<< timeSeries << std::endl;
  IntegerVector embeddingDimension(1);
  embeddingDimension[0]  = RcppDeepState_int();
  qs::c_qsave(embeddingDimension,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/nonlinear_noise_reduction/inputs/embeddingDimension.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "embeddingDimension values: "<< embeddingDimension << std::endl;
  NumericVector radius(1);
  radius[0]  = RcppDeepState_double();
  qs::c_qsave(radius,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/nonlinear_noise_reduction/inputs/radius.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "radius values: "<< radius << std::endl;
  IntegerVector nBoxes(1);
  nBoxes[0]  = RcppDeepState_int();
  qs::c_qsave(nBoxes,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/nonlinear_noise_reduction/inputs/nBoxes.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nBoxes values: "<< nBoxes << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    nonlinear_noise_reduction(timeSeries,embeddingDimension[0],radius[0],nBoxes[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
