// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// getconfusion_DeepState_TestHarness_generation.cpp and getconfusion_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix getconfusion(NumericVector x, NumericVector y, NumericVector ux, NumericVector uy);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mclustcomp/inst/testfiles/getconfusion/libFuzzer_getconfusion/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector y  = RcppDeepState_NumericVector();
  std::string y_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mclustcomp/inst/testfiles/getconfusion/libFuzzer_getconfusion/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_y.qs";
  qs::c_qsave(y,y_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  NumericVector ux  = RcppDeepState_NumericVector();
  std::string ux_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mclustcomp/inst/testfiles/getconfusion/libFuzzer_getconfusion/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ux.qs";
  qs::c_qsave(ux,ux_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ux values: "<< ux << std::endl;
  NumericVector uy  = RcppDeepState_NumericVector();
  std::string uy_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mclustcomp/inst/testfiles/getconfusion/libFuzzer_getconfusion/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_uy.qs";
  qs::c_qsave(uy,uy_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "uy values: "<< uy << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    getconfusion(x,y,ux,uy);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
