// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// calculate_fluctuation_function_DeepState_TestHarness_generation.cpp and calculate_fluctuation_function_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector calculate_fluctuation_function(NumericVector& yr, NumericVector& windowSizesVector);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector yr  = RcppDeepState_NumericVector();
  std::string yr_t = "/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/calculate_fluctuation_function/libFuzzer_calculate_fluctuation_function/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_yr.qs";
  qs::c_qsave(yr,yr_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "yr values: "<< yr << std::endl;
  NumericVector windowSizesVector  = RcppDeepState_NumericVector();
  std::string windowSizesVector_t = "/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/calculate_fluctuation_function/libFuzzer_calculate_fluctuation_function/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_windowSizesVector.qs";
  qs::c_qsave(windowSizesVector,windowSizesVector_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "windowSizesVector values: "<< windowSizesVector << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    calculate_fluctuation_function(yr,windowSizesVector);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
