// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ByteVectorToDoubles_DeepState_TestHarness_generation.cpp and ByteVectorToDoubles_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

DoubleVector ByteVectorToDoubles(IntegerVector b);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector b  = RcppDeepState_IntegerVector();
  std::string b_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mcga/inst/testfiles/ByteVectorToDoubles/AFL_ByteVectorToDoubles/afl_inputs/" + std::to_string(t) + "_b.qs";
  qs::c_qsave(b,b_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "b values: "<< b << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ByteVectorToDoubles(b);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
