// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// nanotime_make_impl_DeepState_TestHarness_generation.cpp and nanotime_make_impl_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericVector nanotime_make_impl(const Rcpp::CharacterVector nt_v, const Rcpp::CharacterVector tz_v);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  CharacterVector nt_v  = RcppDeepState_CharacterVector();
  qs::c_qsave(nt_v,"/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/nanotime_make_impl/inputs/nt_v.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nt_v values: "<< nt_v << std::endl;
  CharacterVector tz_v  = RcppDeepState_CharacterVector();
  qs::c_qsave(tz_v,"/home/akhila/fuzzer_packages/fuzzedpackages/nanotime/inst/testfiles/nanotime_make_impl/inputs/tz_v.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tz_v values: "<< tz_v << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    nanotime_make_impl(nt_v,tz_v);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
