// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// generalized_correlation_sum_DeepState_TestHarness_generation.cpp and generalized_correlation_sum_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix generalized_correlation_sum(const NumericVector& timeSeries, int timeLag, int theilerWindow, NumericVector& radii, int minEmbeddingDim, int maxEmbeddingDim, int corrSumOrder, int numberBoxes);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector timeSeries  = RcppDeepState_NumericVector();
  qs::c_qsave(timeSeries,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/generalized_correlation_sum/inputs/timeSeries.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "timeSeries values: "<< timeSeries << std::endl;
  IntegerVector timeLag(1);
  timeLag[0]  = RcppDeepState_int();
  qs::c_qsave(timeLag,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/generalized_correlation_sum/inputs/timeLag.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "timeLag values: "<< timeLag << std::endl;
  IntegerVector theilerWindow(1);
  theilerWindow[0]  = RcppDeepState_int();
  qs::c_qsave(theilerWindow,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/generalized_correlation_sum/inputs/theilerWindow.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "theilerWindow values: "<< theilerWindow << std::endl;
  NumericVector radii  = RcppDeepState_NumericVector();
  qs::c_qsave(radii,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/generalized_correlation_sum/inputs/radii.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "radii values: "<< radii << std::endl;
  IntegerVector minEmbeddingDim(1);
  minEmbeddingDim[0]  = RcppDeepState_int();
  qs::c_qsave(minEmbeddingDim,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/generalized_correlation_sum/inputs/minEmbeddingDim.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "minEmbeddingDim values: "<< minEmbeddingDim << std::endl;
  IntegerVector maxEmbeddingDim(1);
  maxEmbeddingDim[0]  = RcppDeepState_int();
  qs::c_qsave(maxEmbeddingDim,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/generalized_correlation_sum/inputs/maxEmbeddingDim.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "maxEmbeddingDim values: "<< maxEmbeddingDim << std::endl;
  IntegerVector corrSumOrder(1);
  corrSumOrder[0]  = RcppDeepState_int();
  qs::c_qsave(corrSumOrder,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/generalized_correlation_sum/inputs/corrSumOrder.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "corrSumOrder values: "<< corrSumOrder << std::endl;
  IntegerVector numberBoxes(1);
  numberBoxes[0]  = RcppDeepState_int();
  qs::c_qsave(numberBoxes,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/generalized_correlation_sum/inputs/numberBoxes.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "numberBoxes values: "<< numberBoxes << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    generalized_correlation_sum(timeSeries,timeLag[0],theilerWindow[0],radii,minEmbeddingDim[0],maxEmbeddingDim[0],corrSumOrder[0],numberBoxes[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
