// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cpp_omitMatrix_DeepState_TestHarness_generation.cpp and cpp_omitMatrix_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix cpp_omitMatrix(const NumericMatrix& ExpressionSet, const NumericVector& AgeVector);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix ExpressionSet  = RcppDeepState_NumericMatrix();
  qs::c_qsave(ExpressionSet,"/home/akhila/fuzzer_packages/fuzzedpackages/myTAI/inst/testfiles/cpp_omitMatrix/inputs/ExpressionSet.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ExpressionSet values: "<< ExpressionSet << std::endl;
  NumericVector AgeVector  = RcppDeepState_NumericVector();
  qs::c_qsave(AgeVector,"/home/akhila/fuzzer_packages/fuzzedpackages/myTAI/inst/testfiles/cpp_omitMatrix/inputs/AgeVector.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "AgeVector values: "<< AgeVector << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cpp_omitMatrix(ExpressionSet,AgeVector);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
