// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// dmvn_DeepState_TestHarness_generation.cpp and dmvn_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector dmvn(arma::mat u, arma::mat mu, arma::mat rho);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  std::ofstream u_stream;
  arma::mat u  = RcppDeepState_mat();
  u_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/mets/inst/testfiles/dmvn/inputs/u");
  u_stream << u;
  std::cout << "u values: "<< u << std::endl;
  u_stream.close();
  std::ofstream mu_stream;
  arma::mat mu  = RcppDeepState_mat();
  mu_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/mets/inst/testfiles/dmvn/inputs/mu");
  mu_stream << mu;
  std::cout << "mu values: "<< mu << std::endl;
  mu_stream.close();
  std::ofstream rho_stream;
  arma::mat rho  = RcppDeepState_mat();
  rho_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/mets/inst/testfiles/dmvn/inputs/rho");
  rho_stream << rho;
  std::cout << "rho values: "<< rho << std::endl;
  rho_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    dmvn(u,mu,rho);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
