// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// poincare_map_DeepState_TestHarness_generation.cpp and poincare_map_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List poincare_map(const NumericMatrix& timeSeries, const NumericVector& hiperplanePoint, const NumericVector& normalVector);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix timeSeries  = RcppDeepState_NumericMatrix();
  qs::c_qsave(timeSeries,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/poincare_map/inputs/timeSeries.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "timeSeries values: "<< timeSeries << std::endl;
  NumericVector hiperplanePoint  = RcppDeepState_NumericVector();
  qs::c_qsave(hiperplanePoint,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/poincare_map/inputs/hiperplanePoint.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "hiperplanePoint values: "<< hiperplanePoint << std::endl;
  NumericVector normalVector  = RcppDeepState_NumericVector();
  qs::c_qsave(normalVector,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/poincare_map/inputs/normalVector.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "normalVector values: "<< normalVector << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    poincare_map(timeSeries,hiperplanePoint,normalVector);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
