// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// getVectorNeighbours_DeepState_TestHarness_generation.cpp and getVectorNeighbours_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector getVectorNeighbours(const NumericMatrix& phaseSpace, int vectorIndex, double radius, int numberBoxes);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix phaseSpace  = RcppDeepState_NumericMatrix();
  qs::c_qsave(phaseSpace,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/getVectorNeighbours/inputs/phaseSpace.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "phaseSpace values: "<< phaseSpace << std::endl;
  IntegerVector vectorIndex(1);
  vectorIndex[0]  = RcppDeepState_int();
  qs::c_qsave(vectorIndex,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/getVectorNeighbours/inputs/vectorIndex.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "vectorIndex values: "<< vectorIndex << std::endl;
  NumericVector radius(1);
  radius[0]  = RcppDeepState_double();
  qs::c_qsave(radius,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/getVectorNeighbours/inputs/radius.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "radius values: "<< radius << std::endl;
  IntegerVector numberBoxes(1);
  numberBoxes[0]  = RcppDeepState_int();
  qs::c_qsave(numberBoxes,"/home/akhila/fuzzer_packages/fuzzedpackages/nonlinearTseries/inst/testfiles/getVectorNeighbours/inputs/numberBoxes.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "numberBoxes values: "<< numberBoxes << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    getVectorNeighbours(phaseSpace,vectorIndex[0],radius[0],numberBoxes[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
